### ISSUE TITLE
Can't download the 2G links

### ISSUE THREAD

**Issue by chiphuyen** [jcpeterson/openwebtext#1]
When I clicked on the link https://mega.nz/fm/9BRTBABA, it leads me to my own MEGA homepage. I'm just wondering if anyone else has that problem?

**Comment by NTT123** [comment]
According to this post https://www.reddit.com/r/MachineLearning/comments/as6n7k/p_14_million_urls_for_openwebtext_openai_webtext/ 
the link is https://mega.nz/#F!EZZD0YwJ!9_PlEQzdMVLaNdKv_ICNVQ

**Comment by jcpeterson** [comment]
@NTT123 that's right. @chiphuyen where did you get that link? I should update it

**Comment by NTT123** [comment]
@jcpeterson it's in the README.md file

**Comment by jcpeterson** [comment]
Thanks!

**Comment by jcpeterson** [comment]
fixed

**Comment by chiphuyen** [comment]
Just out of curiosity, why did you remove the link to download these unduplicated URLs?

**Comment by jcpeterson** [comment]
back up now
