### ISSUE TITLE
Getting the karma score from pushshift

### ISSUE THREAD

**Issue by ronnyli** [jcpeterson/openwebtext#15]
Thanks for making such an awesome library!

I just had a question about how the package gets submissions and comments with karma >= `min_karma`. My understanding from the [Pushshift FAQ](https://www.reddit.com/r/pushshift/comments/bcxguf/new_to_pushshift_read_this_faq/) is that Pushshift doesn't have live scores. How did you get around that limitation?

Thanks again :)

**Comment by jcpeterson** [comment]
@ronnyli this just uses whatever pushshift captured at the time
