### ISSUE TITLE
How to cite this version of openwebtext?

### ISSUE THREAD

**Issue by Guitaricet** [jcpeterson/openwebtext#36]
Hi! Do you have any standard bibtex that you recommend to use when citing your work?
I understand that this is a reproduction of Radford et al., but your work deserves credit.

**Comment by Guitaricet** [comment]
**UPD:** I found this bibtex on the OpenWebText website.

```
@misc{Gokaslan2019OpenWeb,  
	title={OpenWebText Corpus},
	author={Aaron Gokaslan and Vanya Cohen},
	howpublished{\url{http://Skylion007.github.io/OpenWebTextCorpus}}, 
	year={2019}
}
```

It would be great to have it in readme (or use the new bibtex feature of GitHub) though.

**Comment by jcpeterson** [comment]
This is a different set of authors
