### ISSUE TITLE
BPE

### ISSUE THREAD

**Issue by 8enmann** [jcpeterson/openwebtext#8]
I'd love to help out and implement BPE. Can you give me some pointers to get started?

**Comment by 8enmann** [comment]
Looks like GPT-2 has code for this
https://github.com/openai/gpt-2/blob/master/src/encoder.py
and another impl here:
https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/tokenization_gpt2.py

**Comment by jcpeterson** [comment]
Thanks, I'll look into this. Do you want to take a stab at integrating?

**Comment by 8enmann** [comment]
I'm thinking of adding an arg to `tokenize_text.py` specifying the encoding type. Happy to look into it.
